name: c9
services:
  mfa-wallet-mock-ase:
    hostname: mfa-wallet-mock-ase
    build:
      context: ../..
      dockerfile: ./localenv/mock-account-servicing-entity/Dockerfile.dev
    restart: always
    networks:
      - rafiki
    ports:
      - '3030:3300'
    environment:
      LOG_LEVEL: debug
      PORT: 80
      SEED_FILE_LOCATION: /workspace/seed.yml
      KEY_FILE: /workspace/private-key.pem
      OPEN_PAYMENTS_URL: ${MFA_OPEN_PAYMENTS_URL:-https://mfa-wallet-backend}
      AUTH_SERVER_DOMAIN: ${MFA_AUTH_SERVER_DOMAIN:-http://localhost:3006}
      TESTNET_AUTOPEER_URL: ${TESTNET_AUTOPEER_URL}
      GRAPHQL_URL: http://mfa-wallet-backend:3001/graphql
      SIGNATURE_VERSION: 1
      SIGNATURE_SECRET: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
      IDP_SECRET: 2pEcn2kkCclbOHQiGNEwhJ0rucATZhrA807HTm2rNXE=
      DISPLAY_NAME: Vote with your wallet
      DISPLAY_ICON: wallet-icon.svg
    volumes:
      - ../mfa/seed.yml:/workspace/seed.yml
      - ../mfa/private-key.pem:/workspace/private-key.pem
    depends_on:
      mfa-wallet-backend:
        condition: service_healthy

  mfa-wallet-backend:
    hostname: mfa-wallet-backend
    image: rafiki-backend
    build:
      context: ../..
      dockerfile: ./packages/backend/Dockerfile.dev
    volumes:
      - type: bind
        source: ../../packages/backend/src
        target: /home/rafiki/packages/backend/src
        read_only: true
    restart: always
    privileged: true
    ports:
      - '3000:80'
      - '3001:3001'
      - '3002:3002'
      - "9229:9229"
    networks:
      - rafiki
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      INSTANCE_NAME: mfa
      TRUST_PROXY: ${TRUST_PROXY}
      LOG_LEVEL: debug
      ADMIN_PORT: 3001
      CONNECTOR_PORT: 3002
      OPEN_PAYMENTS_PORT: 80
      DATABASE_URL: postgresql://mfa_wallet_backend:mfa_wallet_backend@shared-database/mfa_wallet_backend
      USE_TIGERBEETLE: ${USE_TIGERBEETLE-false}
      TIGERBEETLE_CLUSTER_ID: ${TIGERBEETLE_CLUSTER_ID-0}
      TIGERBEETLE_REPLICA_ADDRESSES: ${TIGERBEETLE_REPLICA_ADDRESSES-''}
      AUTH_SERVER_GRANT_URL: ${MFA_AUTH_SERVER_DOMAIN:-http://mfa-wallet-auth:3006}
      AUTH_SERVER_INTROSPECTION_URL: http://mfa-wallet-auth:3007
      ILP_ADDRESS: ${ILP_ADDRESS:-test.mfa-wallet}
      STREAM_SECRET: BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU=
      API_SECRET: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
      OPEN_PAYMENTS_URL: ${MFA_OPEN_PAYMENTS_URL:-http://mfa-wallet-backend}
      WEBHOOK_URL: http://mfa-wallet-backend/webhooks
      EXCHANGE_RATES_URL: http://mfa-wallet-backend/rates
      REDIS_URL: redis://shared-redis:6379/0
      WALLET_ADDRESS_URL: ${MFA_WALLET_ADDRESS_URL:-https://mfa-wallet-backend/.well-known/pay}
      ILP_CONNECTOR_URL: ${MFA_CONNECTOR_URL:-http://mfa-wallet-backend:3002}
      ENABLE_TELEMETRY: true
      KEY_ID: 7097F83B-CB84-469E-96C6-2141C72E22C0
    depends_on:
      - shared-database
      - shared-redis
    healthcheck:
      test: [ "CMD", "wget", "--header=apollo-require-preflight: true", "http://localhost:3001/graphql?query=%7B__typename%7D", "-O", "/dev/null" ]
      start_period: 60s
      start_interval: 5s
      interval: 30s
      retries: 1
      timeout: 3s

  mfa-wallet-auth:
    hostname: mfa-wallet-auth
    build:
      context: ../..
      dockerfile: ./packages/auth/Dockerfile.dev
    volumes:
      - type: bind
        source: ../../packages/auth/src
        target: /home/rafiki/packages/auth/src
    restart: always
    networks:
      - rafiki
    ports:
      - '3003:3003'
      - '3006:3006'
      - "9230:9229"
      - '3009:3009'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      TRUST_PROXY: ${TRUST_PROXY}
      AUTH_DATABASE_URL: postgresql://mfa_wallet_auth:mfa_wallet_auth@shared-database/mfa_wallet_auth
      AUTH_SERVER_URL: ${MFA_AUTH_SERVER_DOMAIN:-http://localhost:3006}
      REDIS_URL: redis://shared-redis:6379/1
      IDENTITY_SERVER_URL: http://localhost:3030/mock-idp/
      IDENTITY_SERVER_SECRET: 2pEcn2kkCclbOHQiGNEwhJ0rucATZhrA807HTm2rNXE=
      COOKIE_KEY: 42397d1f371dd4b8b7d0308a689a57c882effd4ea909d792302542af47e2cd37
      ADMIN_API_SECRET: rPoZpe9tVyBNCigm05QDco7WLcYa0xMao7lO5KG1XG4=
    depends_on:
      - shared-database
      - shared-redis

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "9999:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password

  shared-database:
    image: 'postgres:15' # use latest official postgres version
    restart: unless-stopped
    networks:
      - rafiki
    volumes:
      - database-data2:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ../mfa/dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  shared-redis:
    image: 'redis:7'
    restart: unless-stopped
    networks:
      - rafiki

  mfa-wallet-admin:
    hostname: mfa-wallet-admin
    image: rafiki-frontend
    build:
      context: ../..
      dockerfile: ./packages/frontend/Dockerfile.dev
    volumes:
      - type: bind
        source: ../../packages/frontend/app
        target: /home/rafiki/packages/frontend/app
        read_only: true
    restart: always
    networks:
      - rafiki
    ports:
      - '3010:3010'
    environment:
      PORT: 3010
      LOG_LEVEL: debug
      NODE_ENV: ${NODE_ENV:-development}
      GRAPHQL_URL: http://mfa-wallet-backend:3001/graphql
      OPEN_PAYMENTS_URL: https://mfa-wallet-backend/
      ENABLE_INSECURE_MESSAGE_COOKIE: true
      AUTH_ENABLED: false
      SIGNATURE_VERSION: 1
      SIGNATURE_SECRET: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
    depends_on:
      - mfa-wallet-backend

  happy-life-mock-ase:
    hostname: happy-life-bank
    build:
      context: ../..
      dockerfile: ./localenv/mock-account-servicing-entity/Dockerfile
    pull_policy: never
    restart: always
    networks:
      - rafiki
    ports:
      - '3031:80'
    environment:
      LOG_LEVEL: debug
      PORT: 80
      SEED_FILE_LOCATION: /workspace/seed.yml
      KEY_FILE: /workspace/private-key.pem
      OPEN_PAYMENTS_URL: ${HAPPY_LIFE_BANK_OPEN_PAYMENTS_URL:-https://happy-life-bank-backend}
      GRAPHQL_URL: http://happy-life-bank-backend:3001/graphql
      SIGNATURE_VERSION: 1
      SIGNATURE_SECRET: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
      IDP_SECRET: 2pEcn2kkCclbOHQiGNEwhJ0rucATZhrA807HTm2rNXE=
      DISPLAY_NAME: Happy Life Bank
      DISPLAY_ICON: bank-icon.svg
    volumes:
      - ../happy-life-bank/seed.yml:/workspace/seed.yml
      - ../happy-life-bank/private-key.pem:/workspace/private-key.pem
    depends_on:
      happy-life-backend:
        condition: service_healthy
      mfa-wallet-mock-ase:
        condition: service_started

  happy-life-backend:
    hostname: happy-life-bank-backend
    image: rafiki-backend
    pull_policy: never
    volumes:
      - type: bind
        source: ../../packages/backend/src
        target: /home/rafiki/packages/backend/src
        read_only: true
    restart: always
    privileged: true
    ports:
      - "4000:80"
      - "4001:3001"
      - "4002:3002"
      - '9231:9229'
    networks:
      - rafiki
    environment:
      NODE_ENV: development
      INSTANCE_NAME: HAPPY-LIFE
      LOG_LEVEL: debug
      ADMIN_PORT: 3001
      CONNECTOR_PORT: 3002
      OPEN_PAYMENTS_PORT: 80
      DATABASE_URL: postgresql://happy_life_bank_backend:happy_life_bank_backend@shared-database/happy_life_bank_backend
      USE_TIGERBEETLE: false
      AUTH_SERVER_GRANT_URL: ${HAPPY_LIFE_BANK_AUTH_SERVER_DOMAIN:-http://happy-life-bank-auth:3006}
      AUTH_SERVER_INTROSPECTION_URL: http://happy-life-bank-auth:3007
      ILP_ADDRESS: test.happy-life-bank
      ILP_CONNECTOR_URL: http://happy-life-bank-backend:4002
      STREAM_SECRET: BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU=
      API_SECRET: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
      WEBHOOK_URL: http://happy-life-bank/webhooks
      OPEN_PAYMENTS_URL: ${HAPPY_LIFE_BANK_OPEN_PAYMENTS_URL:-http://happy-life-bank-backend}
      EXCHANGE_RATES_URL: http://happy-life-bank/rates
      REDIS_URL: redis://shared-redis:6379/2
      WALLET_ADDRESS_URL: ${HAPPY_LIFE_BANK_WALLET_ADDRESS_URL:-https://happy-life-bank-backend/.well-known/pay}
      ENABLE_TELEMETRY: true
      KEY_ID: 53f2d913-e98a-40b9-b270-372d0547f23d
    depends_on:
      - mfa-wallet-backend
    healthcheck:
      test: ["CMD", "wget", "--header=apollo-require-preflight: true", "http://localhost:3001/graphql?query=%7B__typename%7D", "-O", "/dev/null"]
      start_period: 60s
      start_interval: 5s
      interval: 30s
      retries: 1
      timeout: 3s

  happy-life-auth:
    hostname: happy-life-bank-auth
    build:
      context: ../..
      dockerfile: ./packages/auth/Dockerfile.dev
    pull_policy: never
    restart: always
    volumes:
      - type: bind
        source: ../../packages/auth/src
        target: /home/rafiki/packages/auth/src
        read_only: true
    networks:
      - rafiki
    ports:
      - '4003:3003'
      - '4006:3006'
      - '9232:9229'
      - '4009:3009'
    environment:
      NODE_ENV: development
      AUTH_DATABASE_URL: postgresql://happy_life_bank_auth:happy_life_bank_auth@shared-database/happy_life_bank_auth
      AUTH_SERVER_URL: ${HAPPY_LIFE_BANK_AUTH_SERVER_DOMAIN:-http://localhost:4006}
      REDIS_URL: redis://shared-redis:6379/3
      IDENTITY_SERVER_URL: http://localhost:3031/mock-idp/
      IDENTITY_SERVER_SECRET: 2pEcn2kkCclbOHQiGNEwhJ0rucATZhrA807HTm2rNXE=
      COOKIE_KEY: 42397d1f371dd4b8b7d0308a689a57c882effd4ea909d792302542af47e2cd37
      ADMIN_API_SECRET: rPoZpe9tVyBNCigm05QDco7WLcYa0xMao7lO5KG1XG4=
    depends_on:
      - mfa-wallet-auth

  happy-life-admin:
    hostname: happy-life-bank-admin
    image: rafiki-frontend
    pull_policy: never
    volumes:
      - type: bind
        source: ../../packages/frontend/app
        target: /home/rafiki/packages/frontend/app
        read_only: true
    restart: always
    networks:
      - rafiki
    ports:
      - '4010:4010'
    environment:
      PORT: 4010
      LOG_LEVEL: debug
      NODE_ENV: development
      GRAPHQL_URL: http://happy-life-bank-backend:3001/graphql
      OPEN_PAYMENTS_URL: https://happy-life-bank-backend/
      ENABLE_INSECURE_MESSAGE_COOKIE: true
      AUTH_ENABLED: false
      SIGNATURE_VERSION: 1
      SIGNATURE_SECRET: iyIgCprjb9uL8wFckR+pLEkJWMB7FJhgkvqhTQR/964=
    depends_on:
      - mfa-wallet-admin
      - happy-life-backend

  mailtrap:
    image: eaudeweb/mailtrap
    ports:
      - "9991:80"
    networks:
      - rafiki

volumes:
  pgadmin-data:
  database-data2: # named volumes can be managed easier using docker-compose
